### ISSUE TITLE
'class AsyncMqttClient' has no member named 'setSecure'

### ISSUE THREAD

**Issue by creativtransfer** [jeroenst/espMQTT#4]
It does not compile, instead complains about 

'class AsyncMqttClient' has no member named 'setSecure'

Which ESP8266-Hardware-Library did you use?

**Comment by creativtransfer** [comment]
When I comment out 
//   mqttClient.setSecure(mqtt_ssl);
it compiles just fine. Is that work in progress or a bug?

**Comment by jeroenst** [comment]
Sorry for my late response, I wasn't aware of your bug report.

You have to set #define ASYNC_TCP_SSL_ENABLED 1 in Arduino/libraries/ESPAsyncTCP/src/async_config.h in order to SSL to work
